server.port=${SERVER_PORT:8080}
server.servlet.context-path=/dfs-crypto-gateway

spring.application.name=dfs-crypto-gateway

dfs.crypto.aes-key=${DFS_AES_KEY:T5wV3hJPn80R8fSunNf6U+gyyThbdAgAghheQZdz5Aw=}
dfs.crypto.replay-window-seconds=30

dfs.downstream.base-url=${DFS_APP_BASE_URL:http://app:8002}
dfs.downstream.dc-url=${DFS_DC_BASE_URL:http://transactions:8009}

dfs.routes[0].path-prefix=/gateway/transactions
dfs.routes[0].downstream-base-url=${dfs.downstream.dc-url}
dfs.routes[0].strip-prefix=/gateway

dfs.routes[1].path-prefix=/gateway/bbs-sdks
dfs.routes[1].downstream-base-url=${dfs.downstream.dc-url}
dfs.routes[1].strip-prefix=/gateway

dfs.routes[2].path-prefix=/gateway
dfs.routes[2].downstream-base-url=${dfs.downstream.base-url}
dfs.routes[2].strip-prefix=/gateway

logging.level.com.dfs=DEBUG
logging.level.org.apache.hc=WARN

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ---- springdoc / Swagger UI ----
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
