spring.application.name=backoffice
server.servlet.context-path=/backoffice
server.port=${SERVER_PORT:8003}

# ---- springdoc / Swagger UI ----
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver
jwt.expiry.time=15
default.session.time=15
workflow.url=${WORKFLOW_BASE_URL:http://workflow:8010}/workflow
jasperJsonFilePath.server=/opt/tomcat/jasperReport/
#jasperJsonFilePath.widnows=C:\\JSON\\
jasperJsonFilePath.widnows=C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0_Tomcat_9.0-oic\\JasperReport\\

account.reg.type.code=A
account.status.active=AS01
account.type.code=30
account.level.three=L3
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
#logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
#logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
#logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
net.sf.jasperreports.awt.ignore.missing.font=true
system.java.awt.headless=true
google.auth.url=${GOOGLEAUTH_BASE_URL}/googleauth
bank.code=BKTY
card.inquiry.url=${CARD_BASE_URL:http://cardwrapper:8005}/cardwrapper/card/

