server.port=${SERVER_PORT:8007}
server.servlet.context-path=/fee

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#Oracle Setting DEV DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver


# ---- springdoc / Swagger UI ----
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# ---- distributed tracing (Sleuth) ----
spring.application.name=pricing-commission
