package com.dfs.backoffice.utils;

public interface Constants {
    String EMPTY = "";
    String ACCEPT = "accept";
    String APPLICATION_JSON = "application/json";
    String CONTENT_TYPE = "content-type";
    String AUTHORIZATION = "Authorization";
    String YES = "Y";
    String NO = "N";
    String UNKNOWN_ENDPOINT = "Unknown Endpoint";
    String GENERAL_PROCESSING_CODE = "2000";
    String GENERAL_PROCESSING_ERROR = "General Processing Error";
    String STARTING_METHOD = "Starting Method :: ";
    String ENDING_METHOD = "Ending Method :: ";
    String LOGIN_SUCCESSFULL = "Login Successfull";
    String LOGIN_UN_SUCCESSFULL = "Login Un-Successfull";
    String LOGOUT_TIME_KEY = "LOGOUT_TIME";
    String LOGOUT_SUCCESSFULL = "Logout Successful";
    String LOGOUT_UN_SUCCESSFULL = "Logout Un-Successful";
    String TABLE_NAME_USER = "TBL_USER";
    String FORM_NAME_USER_ADD = "Create User";
    String REQUEST_TYPE_SAVE = "I";
    String NOT_MAKER_CHECKER = "102010201020";
    String FORM_NAME_USER_EDIT = "Update User";
    String REQUEST_TYPE_UPDATE = "U";
    String ZERO = "0";
    String ONE = "1";
    String UPDATE_TYPE = "A";
    String A = "A";
    String DATE_FROM = "dateFrom";
    String DATE_TO = "dateTo";
    String WRONG_PARAMETER_SET_QUERY = "In Query, Could Not Locate Parameter '";
    String JSON = ".json";
    String WRONG_QUERY_MESSAGE = "Problem With Report Query. Either Query Is Wrong Or Not All Parameters Are Sent";
    String REPORT_FOLDER_NOT_EXIST = "Report Folder Does Not Exist At ";
    String HEADER_NAME_CONTENT_DISPOSITION = "Content-disposition";
    String HEADER_VALUE_CONTENT_DISPOSITION = "attachment;filename=";
    String AFTER_LOGIN ="A" ;
    String LOG_OUT_TIME ="LOGOUT_TIME";
    String ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin";
    String ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods";
    String ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers";
    String ACCESS_CONTROL_ALLOW_CREDENTIALS = "Access-Control-Allow-Credentials";
    String ACCESS_CONTROL_MAX_AGE = "Access-Control-Max-Age";
    String MAX_AGE = "3600";
    String S_1 = "*";
    String S_1_TRUE = "true";
}
