server.port=${SERVER_PORT:8005}
server.servlet.context-path=/cardwrapper
card.api.base.url=${CARD_PROCESSOR_URL}

# ---- distributed tracing (Sleuth) ----
spring.application.name=cardwrapper

# ---- springdoc / Swagger UI ----
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true