package com.dfs.backoffice.dto;

import lombok.Getter;
import lombok.Setter;
import java.util.Date;
import java.math.BigDecimal;

@Getter
@Setter
public class AgentDetailResponse {
    private Long agentId;
    private String fatherHusbandName;
    private String residentialAddress;
    private Long cityId;
    private String cityDescr;
    private Long districtId;
    private String districtDescr;
    private Long provinceId;
    private String provinceDescr;
    private String email;
    private String nok;
    private String name;
    private String occupation;
    private String permanentAddress;
    private String nidNo;
    private String phone;
    private String mobile;
    private Long parentAgentId;
    private String agentCode;
    private String agentType;
    private String isActive;
    private Long statusId;
    private Long createUser;
    private Date createDate;
    private String pob;
    private Date nidIssueDate;
    private Date nidExpiryDate;
    private String grandfatherName;
    private String isFiler;
    private String parentAgent;
    private Long agentClassId;
    private Long agentLevel;
    private String isBlacklisted;
    private String isDeviceRegistered;
    private String lastName;
    private String gender;
    private Date dob;
    private Long customerAllId;
    private String mrzData;
    private BigDecimal facematchScore;
    private BigDecimal livenessScore;
    private String bioverified;
    private String uuid;
    private String otpverified;
    private String selfieverified;
    private String deviceModel;
    private String channelDescr;
    private String accountNo;
    private BigDecimal currentBalance;
    private String iban;
    private String accountTitle;
    private String accountLevelDescr;
    private String accountStatusDescr;
    private BigDecimal dailyAmtLimitDr;
    private BigDecimal monthlyAmtLimitDr;
    private BigDecimal yearlyAmtLimitDr;
    private BigDecimal dailyAmtLimitCr;
    private BigDecimal monthlyAmtLimitCr;
    private BigDecimal yearlyAmtLimitCr;
    private BigDecimal dailyTransLimitDr;
    private BigDecimal monthlyTransLimitDr;
    private BigDecimal yearlyTransLimitDr;
    private BigDecimal dailyTransLimitCr;
    private BigDecimal monthlyTransLimitCr;
    private BigDecimal yearlyTransLimitCr;
    private String nidFront;
    private String nidBack;
    private String proofOfAddress;
    private String selfie;
    private String signature;
    private String license;
    private String shopFront;
    private String shopBack;
    private Long licenseTypeId;
    private String licenseNumber;
    private Date licenseIssueDate;
    private Date licenseExpiryDate;
    private String issuingAuthority;
    private String licenseType;
    private String businessName;
    private String legalStructure;
    private String shopName;
    private Long businessTypeId;
    private String businessTypeName;
    private String businessAddress;
    private String businessDistrict;
    private String businessProvince;
}
