package com.dfs.switchgateway.utils;

/*
Author Name: abdul.fatah

Project Name: switch-gateway

Package Name: com.dfs.switchgateway.utils

Class Name: ResponseCodes

Date and Time:8/16/2023 4:41 PM

Version:1.0
*/
public interface ResponseCodes {
    String PROCESSED_OK = "00";
    String REQUEST_VALIDATION_FAIL = "420";
    String INTERNAL_SERVER_ERROR = "220";
    String LIMIT_EXCEEDED = "01";
    String INVALID_ACCOUNT_PAYER_ACCOUNT_IS_INVALID = "02";
    String ACCOUNT_INACTIVE = "03";
    String LOW_BALANCE = "04";
    String INVALID_CARD = "05";
    String INVALID_IMD = "06";
    String INVALID_CARD_DATA = "07";
    String INVALID_CARD_RECORD = "08";
    String FIELD_ERROR = "09";
    String DUPLICATE_TRANSACTION = "10";
    String BAD_TRANSACTION_CODE = "11";
    String INVALID_CARD_STATUS = "12";
    String INTERNAL_DATABASE_ERROR = "13";
    String WARM_CARD = "14";
    String HOT_CARD = "15";
    String BAD_CARD_STATUS = "16";
    String UNKNOWN_AUTH_MODE = "17";
    String INVALID_TRANSACTION_DATE = "18";
    String INVALID_CURRENCY_CODE = "19";
    String NO_TRANSACTION_ON_IMD_PAYEE_BANK_IS_NOT_ENROLLED = "20";
    String NO_TRANSACTION_ON_ACCT = "21";
    String BAD_CARD_CYCLE_DATE = "22";
    String BAD_CARD_CYCLE_LENGTH = "23";
    String BAD_PIN = "24";
    String CARD_EXPIRED = "25";
    String INTERNAL_ERROR = "26";
    String NO_ACCOUNTS_LINKED = "28";
    String ORIGINAL_TRANSACTION_NOT_FOUND = "30";
    String ORIGINAL_NOT_AUTHORIZED = "34";
    String ORIGINAL_ALREADY_REVERSED = "35";
    String ACQUIRER_REVERSAL = "36";
    String INVALID_REPLACEMENT_AMOUNT = "37";
    String TRANSACTION_CODE_MISMATCH = "38";
    String BAD_TRANSACTION_TYPE_PAYER_BANK_IS_NOT_ENROLLED = "39";
    String EXPIRY_DATE_MISMATCH = "41";
    String ACQUIRER_ADJUSTMENT = "42";
    String ACQUIRER_NACK = "43";
    String ORIGINAL_ALREADY_NACKED = "44";
    String T2_DATA_MISMATCH = "45";
    String UNABLE_TO_PROCESS = "46";
    String ERR_CURRENCY_CONVERSION = "47";
    String BAD_AMOUNT_AMOUNT_RECEIVED_IS_NOT_AGREED_OR_EXPECTED = "48";
    String HOST_STATUS_UNKNOWN = "50";
    String HOST_NOT_PROCESSING = "51";
    String HOST_IN_STANDIN_MODE = "52";
    String HOST_IN_BAL_DWNLD_MODE = "53";
    String SAF_TRANSMIT_MODE = "54";
    String HOST_LINK_DOWN = "55";
    String SENT_TO_HOST = "56";
    String TRANSACTION_TIMEDOUT = "58";
    String HOST_REJECT = "59";
    String PIN_RETRIES_EXHAUSTED = "60";
    String TRANSACTION_REJECTED_SWITCH_TO_CONTACT_INTERFACE = "61";
    String TRANSACTION_REJECTED_PERFORM_TRANSACTION_AGAIN_WITH_CARDHOLDER_AUTHENTICATION_REQUIRED = "62";
    String DESTINATION_NOT_FOUND = "63";
    String DESTINATION_NOT_REGISTERED = "64";
    String CASH_TRANSACTION_NOT_ALLOWED = "65";
    String NO_TRANSACTION_ALLOWED_TRANSACTION_FORBIDDEN_ON_THIS_TYPE_OF_ACCOUNT = "66";
    String INVALID_ACCOUNT_STATUS = "67";
    String INVALID_TO_ACCOUNT = "68";
    String BAD_PIN_COMPARE = "69";
    String REFUSED_IMD = "70";
    String NO_PROFILE_AVAILABLE = "71";
    String CURRENCY_NOT_ALLOWED = "72";
    String CHECK_DIGIT_FAILED = "73";
    String TRANSACTION_SOURCE_NOT_ALLOWED = "74";
    String UNKNOWN_TRANSACTION_SOURCE = "75";
    String MANUAL_ENTRY_NOT_ALLOWED = "76";
    String REFER_TO_ISSUER = "77";
    String INVALID_MERCHANT = "78";
    String HONOR_WITH_ID = "79";
    String MESSAGE_FORMAT_ERROR = "80";
    String SECURITY_VIOLATION = "81";
    String MAIL_ORDER_NOT_ALLOWED = "82";
    String NO_COMMS_KEY = "83";
    String NO_PIN_KEY = "84";
    String NO_DEC_TAB = "85";
    String INCORRECT_PIN_LEN = "86";
    String CASH_RETRACT = "87";
    String FAULTY_DISPENSE = "88";
    String SHORT_DISPENSE = "89";
    String CUSTOMER_NOT_FOUND = "90";
    String ISSUER_REVERSAL = "91";
    String ACCOUNT_LOCKED_PAYER_ACCOUNT_IS_BLOCKED_PROHIBITING_POSTING_OF_TRANSACTION_AGAINST_IT = "92";
    String CUSTOMER_RELATION_NOT_FOUND_PAYER_DECLINED_REQUEST = "93";
    String PERMISSION_DENIED = "94";
    String TRANSACTION_REJECTED = "95";
    String ORIGINAL_ALREADY_REJECTED = "96";
    String BAD_EXP_DATE = "97";
    String ORIGINAL_AMOUNT_INCORRECT = "98";
    String ORIGINAL_DATA_ELEMENT_MISMATCH = "99";
}
