spring.application.name=nadra
logging.level.root=INFO
server.port=${SERVER_PORT:9994}
server.servlet.context-path=/nadra

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging.level.org.springframework.web=info
logging.level.org.springframework.ws.client.MessageTracing.sent=info
logging.level.org.springframework.ws.server.MessageTracing.sent=info
logging.level.org.springframework.ws.client.MessageTracing.received=info
logging.level.org.springframework.ws.server.MessageTracing.received=info


nadra-finger-verification-url=https://localhost:8443/esbnadra/jsnadraservice/v1/VerifyFingerprints
nadra-api-url=https://localhost:8443/esbnadra/JSNadraWebService
nadra-bvs-header-name=Access_token
nadra-bvs-header-value=$67gHS#$123
nadraBvs.mock=Y
nadraBio.mock=Y
nadra.bvs.exemption.mock=N

