spring.application.name=thirdparties
server.servlet.context-path=/thirdparties

# ---- springdoc / Swagger UI ----
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver
server.port=${SERVER_PORT:8008}
sms.template.Type=FWR

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${THIRDPARTIES_MAIL_USERNAME:}
spring.mail.password=${THIRDPARTIES_MAIL_PASSWORD:}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

